services:
  - type: web
    name: note-standard-frontend
    runtime: static
    buildCommand: npm run build --prefix client
    publishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
